on:
    push:
        branches:
        - main
      

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              id: cache
              with:
                path: |
                    target/debug/github-bot
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'src/**') }}
            - name: Cache dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              uses: Swatinem/rust-cache@v2
            - name: build
              if: steps.cache.outputs.cache-hit != 'true'
              run: cargo build