on:
    schedule:
        - cron: "43 */12 * * *"
    workflow_dispatch:


jobs:
    patrol_schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - uses: actions/cache@v4
              id: cache
              with:
                path: |
                    target/debug/qastor
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'src/**') }}
            - name: Cache dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              uses: Swatinem/rust-cache@v2
            - name: build
              if: steps.cache.outputs.cache-hit != 'true'
              run: cargo build
            - name: Launch qastor
              env:
                QASTOR_SECRETS: ${{ secrets.QASTOR_SECRETS }}
                RUST_LOG: debug
              run: target/debug/qastor

