on:
    schedule:
        - cron: "43 */2 * * *"
    workflow_dispatch:
        

jobs:
    patrol_schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Launch qastor
              env:
                QASTOR_SECRETS: ${{ secrets.QASTOR_SECRETS }}
                RUST_LOG: debug
              run: cargo run
