on:
    schedule:
        - cron: "43 */2 * * *"
    workflow_dispatch:


jobs:
    patrol_schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2
            - uses: actions/cache@v4
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: Launch qastor
              env:
                QASTOR_SECRETS: ${{ secrets.QASTOR_SECRETS }}
                RUST_LOG: debug
              run: cargo run
